//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDrop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicDrop.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Drop.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://codeceptive.com.
        /// </summary>
        public static string IDS_About_page_changelog_link {
            get {
                return ResourceManager.GetString("IDS_About_page_changelog_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and review Music Drop.
        /// </summary>
        public static string IDS_About_page_rate_label_text {
            get {
                return ResourceManager.GetString("IDS_About_page_rate_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General info:.
        /// </summary>
        public static string IDS_About_page_support_label_text {
            get {
                return ResourceManager.GetString("IDS_About_page_support_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical questions and support:.
        /// </summary>
        public static string IDS_About_page_tech_label_text {
            get {
                return ResourceManager.GetString("IDS_About_page_tech_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://codeceptive.com/en/#version_history.
        /// </summary>
        public static string IDS_About_page_version_history_link {
            get {
                return ResourceManager.GetString("IDS_About_page_version_history_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version history.
        /// </summary>
        public static string IDS_About_page_version_history_link_content {
            get {
                return ResourceManager.GetString("IDS_About_page_version_history_link_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string IDS_About_page_version_label {
            get {
                return ResourceManager.GetString("IDS_About_page_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application website.
        /// </summary>
        public static string IDS_Application_website_text {
            get {
                return ResourceManager.GetString("IDS_Application_website_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current network interface has invalid type: {0}:{1}.
        /// </summary>
        public static string IDS_Error_invalid_iface {
            get {
                return ResourceManager.GetString("IDS_Error_invalid_iface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connection..
        /// </summary>
        public static string IDS_Error_network_not_available {
            get {
                return ResourceManager.GetString("IDS_Error_network_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found valid interface but cannot find its IP address..
        /// </summary>
        public static string IDS_Error_valid_iface_no_ip {
            get {
                return ResourceManager.GetString("IDS_Error_valid_iface_no_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found valid interface but could not resolve its valid IP: {0}.
        /// </summary>
        public static string IDS_Error_valid_iface_wrong_ip {
            get {
                return ResourceManager.GetString("IDS_Error_valid_iface_wrong_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:info@codeceptive.com.
        /// </summary>
        public static string IDS_Info_email {
            get {
                return ResourceManager.GetString("IDS_Info_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@codeceptive.com.
        /// </summary>
        public static string IDS_Info_email_content {
            get {
                return ResourceManager.GetString("IDS_Info_email_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://codeceptive.com/en/#troubleshooting.
        /// </summary>
        public static string IDS_Main_page_errors_link {
            get {
                return ResourceManager.GetString("IDS_Main_page_errors_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about this error.
        /// </summary>
        public static string IDS_Main_page_errors_link_content {
            get {
                return ResourceManager.GetString("IDS_Main_page_errors_link_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string IDS_Main_page_info_button_text {
            get {
                return ResourceManager.GetString("IDS_Main_page_info_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://codeceptive.com/en/#manual.
        /// </summary>
        public static string IDS_Main_page_manual_link {
            get {
                return ResourceManager.GetString("IDS_Main_page_manual_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to use Music Drop.
        /// </summary>
        public static string IDS_Main_page_manual_link_content {
            get {
                return ResourceManager.GetString("IDS_Main_page_manual_link_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codeceptive Studios.
        /// </summary>
        public static string IDS_Manufacturer_name {
            get {
                return ResourceManager.GetString("IDS_Manufacturer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://codeceptive.com.
        /// </summary>
        public static string IDS_Manufacturer_website {
            get {
                return ResourceManager.GetString("IDS_Manufacturer_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html.
        /// </summary>
        public static string IDS_Server_source_path {
            get {
                return ResourceManager.GetString("IDS_Server_source_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter this URL on your PC to drop music:.
        /// </summary>
        public static string IDS_Server_url_label_text {
            get {
                return ResourceManager.GetString("IDS_Server_url_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:tech@codeceptive.com.
        /// </summary>
        public static string IDS_Tech_email {
            get {
                return ResourceManager.GetString("IDS_Tech_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tech@codeceptive.com.
        /// </summary>
        public static string IDS_Tech_email_content {
            get {
                return ResourceManager.GetString("IDS_Tech_email_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
